# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qt4/main.ui'
#
# Created: Sat Oct 24 11:25:07 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(619, 535)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 601, 76))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 316, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 316, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 90, 601, 351))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_3 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 250, 196, 21))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_17 = QtGui.QPushButton(self.tab_2)
        self.pushButton_17.setEnabled(False)
        self.pushButton_17.setGeometry(QtCore.QRect(510, 280, 80, 30))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtGui.QPushButton(self.tab_2)
        self.pushButton_18.setEnabled(False)
        self.pushButton_18.setGeometry(QtCore.QRect(410, 280, 80, 30))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 226, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 30, 251, 30))
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QtCore.QRect(40, 150, 221, 30))
        self.lineEdit_9.setFrame(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_10.setEnabled(True)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 90, 251, 30))
        self.lineEdit_10.setFrame(True)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.checkBox_7 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 150, 21, 25))
        self.checkBox_7.setObjectName("checkBox_7")
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 210, 251, 30))
        self.lineEdit_8.setFrame(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_11 = QtGui.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(270, 210, 31, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_15 = QtGui.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(270, 30, 31, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 261, 16))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(10, 190, 151, 16))
        self.label_10.setObjectName("label_10")
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 211, 16))
        self.label_19.setObjectName("label_19")
        self.pushButton_12 = QtGui.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(270, 150, 31, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtGui.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(270, 90, 31, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 10, 271, 261))
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 40, 251, 30))
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 53, 15))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_21.setObjectName("label_21")
        self.textBrowser_3 = QtGui.QTextBrowser(self.groupBox_5)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 100, 251, 60))
        self.textBrowser_3.setAcceptRichText(False)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 170, 251, 81))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(70, 10, 121, 25))
        self.label_15.setObjectName("label_15")
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(70, 30, 121, 25))
        self.label_12.setObjectName("label_12")
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setGeometry(QtCore.QRect(70, 50, 121, 25))
        self.label_17.setObjectName("label_17")
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 50, 25))
        self.label_13.setText("0")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 50, 25))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 50, 25))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.checkBox_6 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 280, 271, 21))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 280, 80, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(10, 280, 181, 30))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtGui.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 250, 261, 30))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 261, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 10, 271, 261))
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 251, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 53, 15))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_4.setObjectName("label_4")
        self.textBrowser_2 = QtGui.QTextBrowser(self.groupBox_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 100, 251, 61))
        self.textBrowser_2.setReadOnly(False)
        self.textBrowser_2.setAcceptRichText(False)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 170, 251, 76))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_22 = QtGui.QLabel(self.groupBox_8)
        self.label_22.setGeometry(QtCore.QRect(70, 10, 121, 25))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.groupBox_8)
        self.label_23.setGeometry(QtCore.QRect(70, 30, 121, 25))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.groupBox_8)
        self.label_24.setGeometry(QtCore.QRect(70, 50, 121, 25))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 50, 25))
        self.label_25.setText("0")
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.groupBox_8)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 50, 25))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 50, 25))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.lineEdit_6 = QtGui.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 90, 251, 30))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 261, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_9 = QtGui.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(270, 90, 31, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_7 = QtGui.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 30, 251, 30))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_10 = QtGui.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(270, 30, 31, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 261, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 150, 221, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox_5 = QtGui.QCheckBox(self.tab)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 150, 21, 30))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_4 = QtGui.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 150, 31, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(270, 210, 31, 30))
        self.pushButton.setObjectName("pushButton")
        self.checkBox_4 = QtGui.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 210, 21, 30))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 261, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 210, 221, 30))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.tabWidget.addTab(self.tab, "")
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 449, 601, 76))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.progressBar = QtGui.QProgressBar(self.groupBox_4)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(15, 30, 571, 16))
        self.progressBar.setMinimum(1)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", QtCore.QVariant(100))
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(15, 45, 571, 30))
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 80, 80, 30))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtGui.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 80, 80, 30))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtGui.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(310, 80, 80, 30))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Unofficial Special Installation builder for Pardus Linux", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "PASO", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Dialog", "Don\'t read paso file again", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("Dialog", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("Dialog", "Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Alternative package directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Paso file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Output directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "CD-ROM / Mounted ISO directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Package found", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Needs download", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Download size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Dialog", "Don\'t read alternative packages again", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Go to crazy", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Don\'t read repos again", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Dialog", "Don\'t read installed packages again", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Output directory", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Package found", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Append to paso file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "ISO size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "PARDUS_ROOT", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "CD-ROM / Mounted ISO directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Alternative package directory", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Prepare", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("Dialog", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))

